### ISSUE TITLE
EuclideanRStarTreeKNNQuery NPE

### ISSUE THREAD

**Issue by neilireson** [elki-project/elki#47]
Possibly related to https://github.com/elki-project/elki/issues/46.

NPE thrown, I think because I only have a single data point in the data set.

```
java.lang.NullPointerException
	at de.lmu.ifi.dbs.elki.index.tree.spatial.rstarvariants.query.EuclideanRStarTreeKNNQuery.expandNode(EuclideanRStarTreeKNNQuery.java:105)
	at de.lmu.ifi.dbs.elki.index.tree.spatial.rstarvariants.query.EuclideanRStarTreeKNNQuery.getKNNForObject(EuclideanRStarTreeKNNQuery.java:87)
	at de.lmu.ifi.dbs.elki.index.tree.spatial.rstarvariants.query.EuclideanRStarTreeKNNQuery.getKNNForObject(EuclideanRStarTreeKNNQuery.java:56)
	at de.lmu.ifi.dbs.elki.index.tree.spatial.rstarvariants.query.RStarTreeKNNQuery.getKNNForDBID(RStarTreeKNNQuery.java:94)
	at de.lmu.ifi.dbs.elki.algorithm.clustering.hierarchical.AbstractHDBSCAN.computeCoreDists(AbstractHDBSCAN.java:110)
	at de.lmu.ifi.dbs.elki.algorithm.clustering.hierarchical.HDBSCANLinearMemory.run(HDBSCANLinearMemory.java:116)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at de.lmu.ifi.dbs.elki.algorithm.AbstractAlgorithm.run(AbstractAlgorithm.java:87)
	at de.lmu.ifi.dbs.elki.algorithm.clustering.hierarchical.HDBSCANLinearMemory.run(HDBSCANLinearMemory.java:79)
	at de.lmu.ifi.dbs.elki.algorithm.clustering.hierarchical.extraction.HDBSCANHierarchyExtraction.run(HDBSCANHierarchyExtraction.java:129)
	at uk.ac.shef.wit.active10.CreateStaypoints.cluster(CreateStaypoints.java:707)
	at uk.ac.shef.wit.active10.CreateStaypoints.main(CreateStaypoints.java:1151)
```

**Comment by kno10** [comment]
This indicates a construction problem for a one-point R-tree. I will have a look.
