### ISSUE TITLE
When will the next official version be released? Release 0.7.1 throws ClassCastException in ELKIServiceRegistry

### ISSUE THREAD

**Issue by KilianB** [elki-project/elki#51]
After downloading the new release and trying to launch it via console a ClassCastException was thrown due to line 53 in ELKIServiceRegistry

````Java
private static final URLClassLoader CLASSLOADER = (URLClassLoader) ClassLoader.getSystemClassLoader();
````

The issue apparently is fixed in the current repository
https://github.com/elki-project/elki/blob/ec64a0fade6712aba0f5680971603d5b418c6c76/elki-core-util/src/main/java/de/lmu/ifi/dbs/elki/utilities/ELKIServiceRegistry.java#L43 . 

<details>
<summary>Click to expand stack trace</summary>
<code>
java.lang.ExceptionInInitializerError
        at de.lmu.ifi.dbs.elki.gui.minigui.MiniGUI.setupAppChooser(MiniGUI.java:247)
        at de.lmu.ifi.dbs.elki.gui.minigui.MiniGUI.<init>(MiniGUI.java:198)
        at de.lmu.ifi.dbs.elki.gui.minigui.MiniGUI$9.run(MiniGUI.java:737)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at de.lmu.ifi.dbs.elki.utilities.ELKIServiceRegistry.<clinit>(ELKIServiceRegistry.java:53)
        at de.lmu.ifi.dbs.elki.gui.minigui.MiniGUI.setupAppChooser(MiniGUI.java:247)
        at de.lmu.ifi.dbs.elki.gui.minigui.MiniGUI.<init>(MiniGUI.java:198)
        at de.lmu.ifi.dbs.elki.gui.minigui.MiniGUI$9.run(MiniGUI.java:737)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
</code>
</details>

Java 10 Windows 10

<hr>

I would like to know when the next pre build release will be rolled out.

**Comment by kno10** [comment]
It will be done when its done.
Please use the git version until then.

You can also get current jars via jitpack easily, if you need to use it e.g. in gradle or maven.

**Comment by kno10** [comment]
ELKI 0.7.5 is available on maven now.
